// <auto-generated />
using GestaoDeClientes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoDeClientes.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestaoDeClientes.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClienteCelular");

                    b.Property<string>("ClienteCep");

                    b.Property<string>("ClienteCidade");

                    b.Property<string>("ClienteCpfCnpj");

                    b.Property<string>("ClienteEmail");

                    b.Property<string>("ClienteEmpresa");

                    b.Property<string>("ClienteEndComplem");

                    b.Property<string>("ClienteEstado");

                    b.Property<string>("ClienteNome");

                    b.Property<string>("ClienteNomeFantasia");

                    b.Property<string>("ClienteNumero");

                    b.Property<int>("ClientePerfil");

                    b.Property<string>("ClienteRua");

                    b.Property<string>("ClienteTelefone");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
